Run checks as a standalone script

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -6,9 +6,9 @@
 
 PATH="$(which swiftlint):$(which ruby):$PATH"
 
-if make git-hook-pre-commit; then
-  echo "✅ Quality checked"
+if Scripts/check-quality.sh; then
+	echo "✅ Quality checked"
 else
-  echo "❌ Quality check failed"
-  exit 1
+	echo "❌ Quality check failed"
+	exit 1
 fi
